version: "2.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: "requirements-gpu.txt"
    runtime: nvidia
    volumes:
      - ./:/opt/app
    # command: nvidia-smi
    command: bash
